prefix npx: <http://purl.org/nanopub/x/>
prefix np: <http://www.nanopub.org/nschema#>

select distinct ?np where {
  graph ?h {
    ?np a np:Nanopublication .
    ?np np:hasPublicationInfo ?i .
  }
  graph ?i {
     ?np a npx:ExampleNanopub .
  }
}
