PREFIX npx: <http://purl.org/nanopub/x/>
PREFIX c: <http://rdf.ebi.ac.uk/chembl/>
PREFIX dc: <http://purl.org/dc/terms/>
prefix np: <http://www.nanopub.org/nschema#>
prefix dct: <http://purl.org/dc/terms/>

select (count(distinct ?np) as ?c) ?l where {
  graph ?h {
    ?np a np:Nanopublication .
    ?np np:hasPublicationInfo ?i .
  }
  graph ?i {
        ?np (dct:license|dct:rights) ?l .
  }
} group by ?l order by ?c
